// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package proto.model;

public interface CarMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string carId = 1;</code>
   * @return The carId.
   */
  java.lang.String getCarId();
  /**
   * <code>string carId = 1;</code>
   * @return The bytes for carId.
   */
  com.google.protobuf.ByteString
      getCarIdBytes();

  /**
   * <code>double length = 2;</code>
   * @return The length.
   */
  double getLength();

  /**
   * <code>double acceleration = 3;</code>
   * @return The acceleration.
   */
  double getAcceleration();

  /**
   * <code>double speed = 4;</code>
   * @return The speed.
   */
  double getSpeed();

  /**
   * <code>double maxSpeed = 5;</code>
   * @return The maxSpeed.
   */
  double getMaxSpeed();

  /**
   * <code>string laneId = 6;</code>
   * @return The laneId.
   */
  java.lang.String getLaneId();
  /**
   * <code>string laneId = 6;</code>
   * @return The bytes for laneId.
   */
  com.google.protobuf.ByteString
      getLaneIdBytes();

  /**
   * <code>double positionOnLane = 7;</code>
   * @return The positionOnLane.
   */
  double getPositionOnLane();
}
