// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package proto.model;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\"\212\001\n\nCarMessage\022\r\n\005carId\030\001 " +
      "\001(\t\022\016\n\006length\030\002 \001(\001\022\024\n\014acceleration\030\003 \001(" +
      "\001\022\r\n\005speed\030\004 \001(\001\022\020\n\010maxSpeed\030\005 \001(\001\022\016\n\006la" +
      "neId\030\006 \001(\t\022\026\n\016positionOnLane\030\007 \001(\001B\026\n\013pr" +
      "oto.modelB\005ModelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CarMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CarMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarMessage_descriptor,
        new java.lang.String[] { "CarId", "Length", "Acceleration", "Speed", "MaxSpeed", "LaneId", "PositionOnLane", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
